// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etxshftoozybhaltulcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0eHNoZnRvb3p5YmhhbHR1bGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5Mjk2MDAsImV4cCI6MjA3MDUwNTYwMH0.k5WnBqNdfld0KYiPyvHCVCrHjje4bMsfmCT-Cv7m7DA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});